import type { ScanResult } from "../types/scan";

/**
 * ============================================================
 * SIMULATED AI SERVICE — NOT A REAL PREDICTION
 * ============================================================
 * This file simulates what a real crop-disease AI model would
 * return. It exists so the rest of the app (pages, components)
 * can be built and tested against a realistic data shape now,
 * without depending on a real model or API being ready.
 *
 * TO REPLACE WITH A REAL AI MODEL LATER:
 * - Keep the function name `analyzeCropImage` and its signature
 *   (takes a File, returns Promise<ScanResult>).
 * - Replace the body below with a real API call (e.g. fetch to
 *   your backend / model endpoint), sending the image file and
 *   mapping the real response into the ScanResult shape.
 * - No other file in the app should need to change, since every
 *   caller only depends on this function's signature.
 * ============================================================
 */

const DEMO_RESULTS: ScanResult[] = [
  {
    cropName: "Tomato",
    disease: "Healthy",
    confidence: 97,
    severity: "Low",
    description: "No visible signs of disease were detected on this tomato plant.",
    treatment: "No treatment needed. Continue standard care.",
    prevention: "Maintain regular watering, good spacing, and routine monitoring.",
  },
  {
    cropName: "Tomato",
    disease: "Early Blight",
    confidence: 94,
    severity: "Moderate",
    description: "Possible early blight detected, typically appearing as dark spots on lower leaves.",
    treatment: "Remove infected leaves and improve air circulation around the plant.",
    prevention: "Avoid excessive moisture on leaves and monitor the crop regularly.",
  },
  {
    cropName: "Rice",
    disease: "Rice Blast",
    confidence: 89,
    severity: "High",
    description: "Signs consistent with rice blast were identified, including lesions on leaves.",
    treatment: "Apply appropriate fungicide and remove severely affected plants.",
    prevention: "Use resistant rice varieties and avoid excess nitrogen fertilizer.",
  },
  {
    cropName: "Pepper",
    disease: "Bacterial Leaf Spot",
    confidence: 91,
    severity: "Moderate",
    description: "Small, dark, water-soaked spots on leaves suggest a bacterial leaf disease.",
    treatment: "Remove affected leaves and avoid overhead watering to limit spread.",
    prevention: "Rotate crops each season and use disease-free seed sources.",
  },
];

/**
 * Simulates AI-based crop image analysis.
 * Returns one of several demo results after a short delay to
 * mimic real-world processing time.
 *
 * NOTE: This is a SIMULATED result for development/testing
 * purposes only. It is not generated by a real AI model.
 */
export async function analyzeCropImage(_file: File): Promise<ScanResult> {
  // Simulated processing delay (replace with real request latency later)
  await new Promise((resolve) => setTimeout(resolve, 1800));

  const randomIndex = Math.floor(Math.random() * DEMO_RESULTS.length);
  return DEMO_RESULTS[randomIndex];
}